# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 16:10
from __future__ import unicode_literals

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explination', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=database.models.url)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=database.models.url)),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('ceo', models.CharField(blank=True, max_length=50, null=True)),
                ('founders', models.CharField(blank=True, max_length=50, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(max_length=1000, null=True)),
                ('history', models.CharField(max_length=1000, null=True)),
                ('why_join', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=database.models.url)),
                ('level', models.CharField(choices=[(b'L1', b'LEVEL1'), (b'L2', b'LEVEL2'), (b'L3', b'LEVEL3')], max_length=10)),
                ('company', models.ManyToManyField(blank=True, to='database.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='database.Topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.ManyToManyField(to='database.Year'),
        ),
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_questions', to='database.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='database.SubTopic'),
        ),
        migrations.AddField(
            model_name='company',
            name='founded',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Year'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='database.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='database.Question'),
        ),
    ]
