# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20160924_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='reading',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='data',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
